Update README.md
CptnGreen/robotics21 pull request #2
Opened 2020-07-18 22:21 UTC by CptnGreen

выписал основные вещи, прозвучавшие на видео-встрече, набросал цели бассейна

2020-07-19 08:58 UTC, CptnGreen commented
@bioidiad, @Freimor, я на вас повесил код-ревью (у вас должна была появиться специальная кнопочка - давайте будем эффективно пользоваться инструментами гитхаба), посмотрите, всё ли правильно написал, если нет - отпишитесь, что не так.

2020-07-19 09:41 UTC, CptnGreen commented
Видимо, никто пока не разобрался с тем, как работает код-ревью на гитхабе : )

Всё на самом деле просто - когда какой-то участник делает пул-реквест, он может назначить на этот пул-реквест ревьюверов, т.е. пиров, которые посмотрят, что он сделал, прежде чем изменения будут внесены в основную ветку.

Делается это для того, чтобы, во-первых, все кто нужно был в курсе вносимых изменений и, во-вторых, чтобы сразу исправлять косяки, если такие обнаружатся.

Поэтому реагировать на запросы код-ревью лучше оперативно, чтобы изменения быстрее вносились в проект.

По идее, при запросе код-ревью человеку должно приходить уведомление, после чего он переходит во вкладку pull requests и там для него уже есть кнопка - начать code review. Нажимаешь её, смотришь, пишешь комментарии. После того как все ревьюверы посмотрели, все косяки были найдены и исправлены, изменения можно мёрджить в мастер.

2020-07-19 18:37 UTC, bioidiad requested changes
Точно отменять блок перехода на следующий день, остальное на усмотрение)

2020-07-19 18:37 UTC, bioidiad commented on README.md
> +- первые задания каждого дня нужно сделать "вредными" - их целью будет что-нибудь намеренно "спалить", испортить, короче нарушить технику безопасности
Ты имеешь ввиду, что задание должно быть поставлено так, что бы была вероятность спалить, но пир должен это осознать и не спалить, тогда задание засчитано?

2020-07-19 18:37 UTC, bioidiad commented on README.md
> +- участник не может перейти в следующий день, если он не сдал "вредные задания" (т.к. они на технику безопасности)
Да, пожалуй нет - может, просто нужно определить критическую массу таких фейлов, после которой фейлится бассейн

2020-07-19 18:37 UTC, bioidiad commented on README.md
> +- управление роботом по проводам, через bluetooth, через wifi
Можно ещё по ик, с этого начать беспроводную тематику.

2020-07-19 19:28 UTC, merged

2020-07-20 21:39 UTC, CptnGreen commented on README.md
> +- первые задания каждого дня нужно сделать "вредными" - их целью будет что-нибудь намеренно "спалить", испортить, короче нарушить технику безопасности
Да, даётся какая-то ситуация, изначально всё хорошо, всё работает, и поначалу даже непонятно, что может пойти не так, потому что кажется, что спалить тут спалить невозможно. Задача - проявить смекалку и всё-таки что-нибудь сломать (испортить компонент, устроить пожар и т.д.)

Речь идёт про теоретические задания или задания на симуляторе

2020-07-20 21:42 UTC, CptnGreen commented on README.md
> +- участник не может перейти в следующий день, если он не сдал "вредные задания" (т.к. они на технику безопасности)
@bioidiad, думаю, критериям фейлов (особенно преждевременных) на бассейне стоит посвятить отдельное обсуждение

2020-07-20 21:42 UTC, CptnGreen commented on README.md
> +- управление роботом по проводам, через bluetooth, через wifi
@bioidiad, только за, чем больше, тем лучше

2020-07-21 13:31 UTC, bioidiad commented on README.md
> +- первые задания каждого дня нужно сделать "вредными" - их целью будет что-нибудь намеренно "спалить", испортить, короче нарушить технику безопасности
Не совсем то, о чем я, но не суть. В целом мысль ясна, думаю при подготовке заданий станет понятно, что лучше.